# WARNING: this file was autogenerated by generate-base-slim-image.js
set e+x

# build image with Cypress dependencies
LOCAL_NAME=cypress/base:12.16.2-slim

echo "Building $LOCAL_NAME"
docker build -t $LOCAL_NAME .
