# WARNING: this file was autogenerated by generate-browser-image.js
# using
#   yarn add:browsers -- 16.14.0-slim --chrome=99.0.4844 --firefox=97.0.1
set e+x

LOCAL_NAME=cypress/browsers:node16.14.0-slim-chrome99-ff97
echo "Building $LOCAL_NAME"
docker build -t $LOCAL_NAME .
