# WARNING: this file was autogenerated by generate-included-image.js
# using
#   npm run add:included -- 5.6.0-14 cypress/browsers:node14.15.0-chrome86-ff82
set e+x

LOCAL_NAME=cypress/included:5.6.0-14
echo "Building $LOCAL_NAME"
docker build -t $LOCAL_NAME .
