# WARNING: this file was autogenerated by generate-browser-image.js
# using
#   yarn add:browser -- 14.15.0 --chrome=105.0.5195.125 --firefox=105.0
set e+x

LOCAL_NAME=cypress/browsers:node14.15.0-chrome105-ff105
echo "Building $LOCAL_NAME"
docker build -t $LOCAL_NAME .
