# the image name placeholder below is replaced in circle.yml
FROM InsertBaseImageHere
RUN echo "current user: $(whoami)"
ENV CI=1
COPY ./test-project /app
WORKDIR /app
RUN npm install --save-dev cypress
RUN ./node_modules/.bin/cypress verify