# WARNING: this file was autogenerated by generate-included-image.js
# using
#   npm run add:included -- 10.3.1 cypress/browsers:node14.19.0-chrome100-ff99-edge
set e+x

LOCAL_NAME=cypress/included:10.3.1
echo "Building $LOCAL_NAME"
docker build -t $LOCAL_NAME .
