# WARNING: this file was autogenerated by generate-browser-image.js
# using
#   yarn add:browser -- 16.18.0 --chrome=90.0.4430.212 --firefox=88.0.1
set e+x

LOCAL_NAME=cypress/browsers:node16.18.0-chrome90-ff88
echo "Building $LOCAL_NAME"
docker build -t $LOCAL_NAME .
