# WARNING: this file was autogenerated by generate-included-image.js
# using
#   npm run add:included -- 10.3.0 cypress/browsers:node16.14.0-edge
set e+x

LOCAL_NAME=cypress/included:10.3.0-node16.14.0-edge
echo "Building $LOCAL_NAME"
docker build -t $LOCAL_NAME .
