# WARNING: this file was autogenerated by generate-base-image.js
set e+x

# build image with Cypress dependencies
LOCAL_NAME=cypress/base:16.14.0-slim

echo "Building $LOCAL_NAME"
docker build -t $LOCAL_NAME .
