# WARNING: this file was autogenerated by generate-included-image.js
# using
#   npm run add:included -- 9.5.2 cypress/browsers:node14.18.1-chrome108
set e+x

LOCAL_NAME=cypress/included:9.5.2-node14.18.1-chrome108
echo "Building $LOCAL_NAME"
docker build -t $LOCAL_NAME .
