# WARNING: this file was autogenerated by generate-included-image.js
# using
#   npm run add:included -- 9.4.1 cypress/browsers:node16.13.0-slim-chrome95-ff94
set e+x

LOCAL_NAME=cypress/included:9.4.1-node16.13.0-slim-chrome95-ff94
echo "Building $LOCAL_NAME"
docker build -t $LOCAL_NAME .
