# WARNING: this file was autogenerated by generate-included-image.js
# using
#   npm run add:included -- 8.3.0 node14.16.0-slim-chrome90-ff88
set e+x

LOCAL_NAME=cypress/included:8.3.0
echo "Building $LOCAL_NAME"
docker build -t $LOCAL_NAME .
