version: '3.8'

services:
  factory:
    image: cypress/factory
    build:
      dockerfile: factory.Dockerfile
      target: factory
      context: .
      args:
        BASE_IMAGE: ${BASE_IMAGE}
        DEFAULT_NODE_VERSION: ${NODE_VERSION}
      tags:
       - cypress/factory:latest
       - cypress/factory:${FACTORY_VERSION}
    command: node -v
  included:
    image: cypress/included
    build:
      target: included_image
      context: .
      args:
        CHROME_VERSION: ${CHROME_VERSION}
        CYPRESS_VERSION: ${CYPRESS_VERSION}
        EDGE_VERSION: ${EDGE_VERSION}
        FIREFOX_VERSION: ${FIREFOX_VERSION}
        YARN_VERSION: ${YARN_VERSION}
        # WEBKIT_VERSION: ${WEBKIT_VERSION}
      tags:
       - cypress/included:latest
       - cypress/included:${CYPRESS_VERSION} #Using the cypress version here doesn't feel right.
    command: node -v
  base:
    image: cypress/base
    build:
      target: default_image
      context: .
      args:
        YARN_VERSION: ${YARN_VERSION}
      tags:
       - cypress/base:latest
       - cypress/base:${NODE_VERSION}
    command: node -v
  chrome:
    image: "cypress/chrome"
    build:
      target: default_image
      context: .
      args:
        CHROME_VERSION: ${CHROME_VERSION}
      tags:
       - cypress/chrome:latest
       - cyrpess/chrome:${CHROME_VERSION}
    command: google-chrome --version
  edge:
    image: cypress/edge
    build:
      target: default_image
      context: .
      args:
        EDGE_VERSION: ${EDGE_VERSION}
      tags:
       - cypress/edge:latest
       - cyrpess/edge:${EDGE_VERSION}
    command: edge --version
  firefox:
    image: cypress/firefox
    build:
      target: default_image
      context: .
      args:
        FIREFOX_VERSION: ${FIREFOX_VERSION}
      tags:
       - cypress/firefox:latest
       - cyrpess/firefox:${FIREFOX_VERSION}
    command: firefox --version
  # webkit:
  #   image: cypress/webkit
  #   build:
  #     target: default_image
  #     context: .
  #     args:
  #       WEBKIT_VERSION: ${WEBKIT_VERSION}
  #     tags:
  #     - cypress/webkit:latest
  #     - cyrpess/webkit:${WEBKIT_VERSION}
  #   command: webkit --version
  cypress:
    image: cypress/cypress
    build:
      target: default_image
      context: .
      args:
        CYPRESS_VERSION: ${CYPRESS_VERSION}
      tags:
       - cypress/cypress:latest
       - cyrpess/cypress:${CYPRESS_VERSION}
    command: cypress verify
  cypress-chrome:
    image: cypress/cypress-chrome
    build:
      target: default_image
      context: .
      args:
        CYPRESS_VERSION: ${CYPRESS_VERSION}
        CHROME_VERSION: ${CHROME_VERSION}
      tags:
       - cypress/cypress-chrome:latest
       - cyrpess/cypress-chrome:cypress-${CYPRESS_VERSION}-chrome-${CHROME_VERSION}
    command: node -v
  cypress-edge:
    image: cypress/cypress-edge
    build:
      target: default_image
      context: .
      args:
        CYPRESS_VERSION: ${CYPRESS_VERSION}
        EDGE_VERSION: ${EDGE_VERSION}
      tags:
       - cypress/cypress-edge:latest
       - cyrpess/cypress-edge:cypress-${CYPRESS_VERSION}-edge-${EDGE_VERSION}
    command: node -v
  cypress-firefox:
    image: cypress/cypress-firefox
    build:
      target: default_image
      context: .
      args:
        CYPRESS_VERSION: ${CYPRESS_VERSION}
        FIREFOX_VERSION: ${FIREFOX_VERSION}
      tags:
       - cypress/cypress-firefox:latest
       - cyrpess/cypress-firefox:cypress-${CYPRESS_VERSION}-firefox-${FIREFOX_VERSION}
    command: node -v
  browsers:
    image: cypress/browsers
    build:
      target: default_image
      context: .
      args:
        YARN_VERSION: ${YARN_VERSION}
        CHROME_VERSION: ${CHROME_VERSION}
        FIREFOX_VERSION: ${FIREFOX_VERSION}
        EDGE_VERSION: ${EDGE_VERSION}
      tags:
       - cypress/browsers:latest
       - cyrpess/browsers:node-${NODE_VERSION}-chrome-${CHROME_VERSION}-ff-${FIREFOX_VERSION}-edge-${EDGE_VERSION}
    command: node -v
  test-node-override:
    build:
      target: default_image
      context: .
      args:
        NODE_VERSION: 16.17.0
    command: node -v
