version: '3.8'

services:
  factory:
    image: "cypress/factory"
    build:
      dockerfile: factory.Dockerfile
      target: factory
      context: .
      args:
        BASE_IMAGE: debian:bullseye-slim
        DEFAULT_NODE_VERSION: &default-node-version '16.18.1'
      # tags:
      #  - cypress/factory:latest
      #  - cypress/factory:1
      #  - cypress/factory:1.1
      #  - cypress/factory:1.0.0
    command: node -v
  included:
    image: "cypress/included"
    build:
      target: included_image
      context: .
      args:
        # NODE_VERSION is set as a default in the docker container
        # Node Versions: https://nodejs.org/en/download/releases/
        CHROME_VERSION: &chrome-version '107.0.5304.121-1'
        # Chrome versions: https://www.ubuntuupdates.org/package/google_chrome/stable/main/base/google-chrome-stable
        CYPRESS_VERSION: &cypress-version '12.1.0'
        # Cypress versions: https://www.npmjs.com/package/cypress
        EDGE_VERSION: &edge-version '110.0.1556.0-1'
        # Edge versions: https://packages.microsoft.com/repos/edge/pool/main/m/microsoft-edge-stable/
        FIREFOX_VERSION: &firefox-version '107.0'
        # Firefox versions: https://download-installer.cdn.mozilla.net/pub/firefox/releases/
        YARN_VERSION: &yarn-version '1.22.19'
        # Yarn versions: https://www.npmjs.com/package/yarn
    command: node -v
  base:
    image: "cypress/base"
    build:
      target: default_image
      context: .
      args:
        YARN_VERSION: *yarn-version
    command: node -v
  chrome:
    image: "cypress/chrome"
    build:
      target: default_image
      context: .
      args:
        CHROME_VERSION: *chrome-version
    command: google-chrome --version
  edge:
    image: "cypress/edge"
    build:
      target: default_image
      context: .
      args:
        EDGE_VERSION: *edge-version
    command: edge --version
  firefox:
    image: "cypress/firefox"
    build:
      target: default_image
      context: .
      args:
        FIREFOX_VERSION: *firefox-version
    command: firefox --version
  cypress:
    image: "cypress/cypress"
    build:
      target: default_image
      context: .
      args:
        CYPRESS_VERSION: *cypress-version
    command: cypress verify
  cypress-chrome:
    image: "cypress/cypress-chrome"
    build:
      target: default_image
      context: .
      args:
        CYPRESS_VERSION: *cypress-version
        CHROME_VERSION: *chrome-version
    command: node -v
  cypress-edge:
    image: "cypress/cypress-edge"
    build:
      target: default_image
      context: .
      args:
        CYPRESS_VERSION: *cypress-version
        EDGE_VERSION: *edge-version
    command: node -v
  cypress-firefox:
    image: "cypress/cypress-firefox"
    build:
      target: default_image
      context: .
      args:
        CYPRESS_VERSION: *cypress-version
        FIREFOX_VERSION: *firefox-version
    command: node -v
  browsers:
    image: "cypress/browsers"
    build:
      target: default_image
      context: .
      args:
        YARN_VERSION: *yarn-version
        CHROME_VERSION: *chrome-version
        FIREFOX_VERSION: *firefox-version
        EDGE_VERSION: *edge-version
    command: node -v
  node-override:
    build:
      target: default_image
      context: .
      args:
        NODE_VERSION: 16.17.0
    command: node -v
