version: '3'

services:
  base:
    build:
      target: base
      context: .
      args:
        NODE_VERSION: '16.18.1'
    command: node -v
  chrome:
    build:
      target: chrome
      context: .
      args:
        NODE_VERSION: '16.18.1'
        CHROME_VERSION: '107.0.5304.121-1'
    command: node -v
  final:
    build:
      target: final
      context: .
      args:
        NODE_VERSION: '16.18.1'
        CHROME_VERSION: '107.0.5304.121-1'
        FIREFOX_VERSION: '107.0'
        EDGE: 'true'
        CYPRESS_VERSION: '12.0.1'
    command: node -v
  firefox:
    build:
      target: firefox
      context: .
      args:
        NODE_VERSION: '16.18.1'
        FIREFOX_VERSION: '107.0'
    command: node -v
  edge:
    build:
      target: edge
      context: .
      args:
        NODE_VERSION: '16.18.1'
        FIREFOX_VERSION: '107.0'
    command: node -v
