# WARNING: this file was autogenerated by generate-included-image.js
# using
#   npm run add:included -- 5.4.0 cypress/browsers:node12.19.0-chrome86-ff82
set e+x

LOCAL_NAME=cypress/included:5.4.0
echo "Building $LOCAL_NAME"
docker build -t $LOCAL_NAME .
