# WARNING: this file was autogenerated by generate-browser-image.js
# using
#   yarn add:browser -- 16.17.0 --chrome=104.0.5112.101
set e+x

LOCAL_NAME=cypress/browsers:node16.17.0-chrome104
echo "Building $LOCAL_NAME"
docker build -t $LOCAL_NAME .
