# WARNING: this file was autogenerated by generate-browser-image.js
# using
#   yarn add:browser -- 16.14.2 --edge=99.0.1150.55
set e+x

LOCAL_NAME=cypress/browsers:node16.14.2-edge99
echo "Building $LOCAL_NAME"
docker build -t $LOCAL_NAME .
