# WARNING: this file was autogenerated by generate-browser-image.js
# using
#   yarn add:browser -- 14.19.0 --chrome=97.0.4692.71 --firefox=102.0.1
set e+x

LOCAL_NAME=cypress/browsers:node14.19.0-chrome97-ff102
echo "Building $LOCAL_NAME"
docker build -t $LOCAL_NAME .
