# WARNING: this file was autogenerated by generate-included-image.js
# using
#   npm run add:included -- 12.2.0 cypress/browsers:node16.18.0-chrome107-ff106-edge
set e+x

LOCAL_NAME=cypress/included:12.2.0
echo "Building $LOCAL_NAME"
docker build -t $LOCAL_NAME .
