# WARNING: this file was autogenerated by generate-browser-image.js
# using
#   yarn add:browser -- 16.14.2-slim --chrome=103.0.5060.53 --firefox=99.0.1
set e+x

LOCAL_NAME=cypress/browsers:node16.14.2-slim-chrome103-ff99-slim
echo "Building $LOCAL_NAME"
docker build -t $LOCAL_NAME .
