# WARNING: this file was autogenerated by generate-browser-image.js
# using
#   yarn add:browsers -- 16.5.0 --chrome=94.0.4606.71 --firefox=93.0
set e+x

LOCAL_NAME=cypress/browsers:node16.5.0-chrome94-ff93
echo "Building $LOCAL_NAME"
docker build -t $LOCAL_NAME .
