# WARNING: this file was autogenerated by generate-included-image.js
# using
#   npm run add:included -- 9.5.4 cypress/browsers:node16.14.0-slim-chrome99-ff97
set e+x

LOCAL_NAME=cypress/included:9.5.4
echo "Building $LOCAL_NAME"
docker build -t $LOCAL_NAME .
