# WARNING: this file was autogenerated by generate-browser-image.js
# using
#   yarn add:browser -- 18.12.0 --chrome=103.0.5060.134 --firefox=107.0
set e+x

LOCAL_NAME=cypress/browsers:node18.12.0-chrome103-ff107
echo "Building $LOCAL_NAME"
docker build -t $LOCAL_NAME .
