# WARNING: this file was autogenerated by generate-base-image.js
set e+x

# build image with Cypress dependencies
LOCAL_NAME=cypress/base:14.15.4-npm-6.14.10

echo "Building $LOCAL_NAME"
docker build -t $LOCAL_NAME .
