# WARNING: this file was autogenerated by generate-browser-image.js
# using
#   yarn add:browser -- 17.8.0 --chrome=99.0.4844.84 --firefox=97.0.1
set e+x

LOCAL_NAME=cypress/browsers:node17.8.0-chrome99-ff97
echo "Building $LOCAL_NAME"
docker build -t $LOCAL_NAME .
