# WARNING: this file was autogenerated by generate-browser-image.js
# using
#   yarn add:browser -- 16.14.2-slim --chrome=99.0.4844.51 --firefox=97.0.1 --edge
set e+x

LOCAL_NAME=cypress/browsers:node16.14.2-slim-chrome99-ff97-edge
echo "Building $LOCAL_NAME"
docker build -t $LOCAL_NAME .
