# WARNING: this file was autogenerated by generate-browser-image.js
# using
#   yarn add:browser -- 18.12.0 --chrome=106.0.5249.91 --firefox=106.0.2
set e+x

LOCAL_NAME=cypress/browsers:node18.12.0-chrome106-ff106
echo "Building $LOCAL_NAME"
docker build -t $LOCAL_NAME .
