# WARNING: this file was autogenerated by generate-included-image.js
# using
#   npm run add:included -- 6.6.0 cypress/browsers:node14.15.0-chrome86-ff82-slim
set e+x

LOCAL_NAME=cypress/included:6.6.0-node14.15.0-chrome86-ff82-slim
echo "Building $LOCAL_NAME"
docker build -t $LOCAL_NAME .
