# WARNING: this file was autogenerated by generate-included-image.js
# using
#   npm run add:included -- 4.0.0 cypress/browsers:node13.6.0-chrome-80-ff72
set e+x

LOCAL_NAME=cypress/included:4.0.0
echo "Building $LOCAL_NAME"
docker build -t $LOCAL_NAME .
