# WARNING: this file was autogenerated by generate-browser-image.js
# using
#   yarn add:browser -- 14.18.1 --chrome=100
set e+x

LOCAL_NAME=cypress/browsers:node14.18.1-chrome
echo "Building $LOCAL_NAME"
docker build -t $LOCAL_NAME .
