# WARNING: this file was autogenerated by generate-browser-image.js
# using
#   yarn add:browser -- 16.17.1 --chrome=106.0.5249.91 --firefox=105.0.1 --edge
set e+x

LOCAL_NAME=cypress/browsers:node16.17.1-chrome106-ff105-edge
echo "Building $LOCAL_NAME"
docker build -t $LOCAL_NAME .
