# WARNING: this file was autogenerated by generate-browser-image.js
# using
#   yarn add:browsers -- 16.14.0-slim --chrome=97.0.4692.71 --firefox=96.0.2
set e+x

LOCAL_NAME=cypress/browsers:node16.14.0-slim-chrome97-ff96
echo "Building $LOCAL_NAME"
docker build -t $LOCAL_NAME .
