# WARNING: this file was autogenerated by generate-browser-image.js
# using
#   yarn add:browser -- 18.6.0 --firefox=104.0.1 --chrome=105.0.5195.102
set e+x

LOCAL_NAME=cypress/browsers:node18.6.0-chrome105-ff104
echo "Building $LOCAL_NAME"
docker build -t $LOCAL_NAME .
